---
apiVersion: v1
kind: Service
metadata:
  name: nginx-demo
  namespace: demo-nginx
spec:
  selector:
    app: nginx-demo
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP